name: Pulumi Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stack-name:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.20"
          enable-cache: true
      - name: Install the project
        run: uv sync
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
