name: Pulumi Staging Workflow

on: [push]

concurrency:
  group: merge-${{ github.ref }}

jobs:
  deploy:
    uses: ./.github/workflows/pulumi.deploy.yml
    with:
      environment: Staging
      stack-name: staging
    secrets: inherit
