name: Pulumi Staging Workflow
on: [push]

concurrency:
  group: merge-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: staging
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
