name: Pulumi Production Workflow

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

concurrency:
  group: merge-${{ github.ref }}

jobs:
  deploy:
    uses: ./.github/workflows/pulumi.deploy.yml
    with:
      environment: Production
      stack-name: prod
    secrets: inherit
